version: '3.10'


services:
  web:
    build: .
    command: gunicorn spinner_smm.wsgi:application --bind 0.0.0.0:10001
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 1001
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 10001:80
    depends_on:
      - web


volumes:
  static_volume:
  media_volume: