# Generated by Django 4.2.4 on 2023-09-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_rename_recordings_recording'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='date_updated',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='date_created',
        ),
    ]
