# Generated by Django 4.2.4 on 2023-09-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_rename_date_updated_recording_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='content',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='recording',
            old_name='title',
            new_name='titre',
        ),
    ]
