# Generated by Django 4.2.4 on 2023-09-08 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_rename_content_recording_contenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording_extend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(default='', max_length=255)),
                ('contenu', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recording_rewrite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(default='', max_length=255)),
                ('contenu', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
