# Generated by Django 4.2.4 on 2023-09-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0006_rename_id_recording_res_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='contenu',
            new_name='contenu1',
        ),
        migrations.RenameField(
            model_name='recording',
            old_name='titre',
            new_name='titre1',
        ),
    ]
