# Generated by Django 4.2.4 on 2023-09-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0007_rename_contenu_recording_contenu1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recording',
            new_name='Summary',
        ),
    ]
