# Generated by Django 4.2.4 on 2023-09-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0008_rename_recording_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='contenu1',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='titre1',
            new_name='titre',
        ),
    ]
