# Generated by Django 4.2.4 on 2023-09-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0009_rename_contenu1_summary_contenu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording_extend',
            old_name='ext_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='recording_rewrite',
            old_name='rew_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='res_id',
            new_name='id',
        ),
    ]
