# Generated by Django 4.2.4 on 2023-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0011_alter_recording_extend_contenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording_extend',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recording_extend',
            name='titre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='recording_rewrite',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recording_rewrite',
            name='titre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='titre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
